/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package primerintentocostos.gui;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import primerintentocostos.logica.Material;

/**
 *
 * @author franc
 */
public class ActualizacionPrecios extends javax.swing.JFrame {
    private final ArrayList<Material> materiales;
    /**
     * Creates new form ActualizacionPrecios
     * @param materiales
     */
    public ActualizacionPrecios(ArrayList<Material> materiales) {
        initComponents();
        this.materiales = materiales;
    }
    
    private void actualizarPrecio(int indice, int precioActualizado){
        int precioAnterior = materiales.get(indice).getPrecio();
        materiales.get(indice).setPrecio(precioActualizado);
        JOptionPane optionPane = new JOptionPane("Se actualizo el precio de $" + precioAnterior + " a $" + precioActualizado);
        optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        JDialog dialog = optionPane.createDialog("Actualizacion de precio");
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFBNOracal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFDoradoMcCal = new javax.swing.JTextField();
        txtFTorna = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFTransferUnical = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFTransferAdere = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnActuBNOracal = new javax.swing.JButton();
        btnActuDoradoMcCal = new javax.swing.JButton();
        btnActuTorna = new javax.swing.JButton();
        btnActuTransferAdere = new javax.swing.JButton();
        btnActuTransferUnical = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFOtro = new javax.swing.JTextField();
        btnActuOtro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR PRECIOS");

        jLabel2.setText("Negro/Blanco Oracal 100");

        jLabel3.setText("Dorado metalizado McCal");

        jLabel4.setText("$");

        jLabel5.setText("$");

        jLabel6.setText("Tornasolado");

        jLabel7.setText("$");

        jLabel8.setText("Transfer UNICAL");

        jLabel9.setText("$");

        jLabel10.setText("Transfer ADERE");

        jLabel11.setText("$");

        btnActuBNOracal.setText("Actualizar");
        btnActuBNOracal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuBNOracalActionPerformed(evt);
            }
        });

        btnActuDoradoMcCal.setText("Actualizar");
        btnActuDoradoMcCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuDoradoMcCalActionPerformed(evt);
            }
        });

        btnActuTorna.setText("Actualizar");
        btnActuTorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuTornaActionPerformed(evt);
            }
        });

        btnActuTransferAdere.setText("Actualizar");
        btnActuTransferAdere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuTransferAdereActionPerformed(evt);
            }
        });

        btnActuTransferUnical.setText("Actualizar");
        btnActuTransferUnical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuTransferUnicalActionPerformed(evt);
            }
        });

        jLabel12.setText("Otro");

        jLabel13.setText("$");

        btnActuOtro.setText("Actualizar");
        btnActuOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuOtroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFTorna, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActuTorna))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFDoradoMcCal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActuDoradoMcCal))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFBNOracal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnActuBNOracal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnActuOtro))
                                .addComponent(jLabel12)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFTransferUnical, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActuTransferUnical))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFTransferAdere, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnActuTransferAdere))))))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFBNOracal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(btnActuBNOracal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFTransferUnical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnActuTransferUnical))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFDoradoMcCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnActuDoradoMcCal)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFTransferAdere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(btnActuTransferAdere))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFTorna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnActuTorna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFOtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnActuOtro))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActuTornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuTornaActionPerformed
        int actuTorna = Integer.parseInt(txtFTorna.getText());
        actualizarPrecio(2, actuTorna);
    }//GEN-LAST:event_btnActuTornaActionPerformed

    private void btnActuTransferAdereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuTransferAdereActionPerformed
        int actuAdere= Integer.parseInt(txtFTransferAdere.getText());
        actualizarPrecio(5, actuAdere);
    }//GEN-LAST:event_btnActuTransferAdereActionPerformed

    private void btnActuTransferUnicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuTransferUnicalActionPerformed
        int actuUnical= Integer.parseInt(txtFTransferUnical.getText());
        actualizarPrecio(4, actuUnical);
    }//GEN-LAST:event_btnActuTransferUnicalActionPerformed

    private void btnActuBNOracalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuBNOracalActionPerformed
        int actuBNOracal = Integer.parseInt(txtFBNOracal.getText());
        actualizarPrecio(0, actuBNOracal);
    }//GEN-LAST:event_btnActuBNOracalActionPerformed

    private void btnActuDoradoMcCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuDoradoMcCalActionPerformed
        int actuDoradoMcCal = Integer.parseInt(txtFDoradoMcCal.getText());
        actualizarPrecio(1, actuDoradoMcCal);
    }//GEN-LAST:event_btnActuDoradoMcCalActionPerformed

    private void btnActuOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuOtroActionPerformed
        int actuOtro = Integer.parseInt(txtFOtro.getText());
        actualizarPrecio(3, actuOtro);
    }//GEN-LAST:event_btnActuOtroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuBNOracal;
    private javax.swing.JButton btnActuDoradoMcCal;
    private javax.swing.JButton btnActuOtro;
    private javax.swing.JButton btnActuTorna;
    private javax.swing.JButton btnActuTransferAdere;
    private javax.swing.JButton btnActuTransferUnical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFBNOracal;
    private javax.swing.JTextField txtFDoradoMcCal;
    private javax.swing.JTextField txtFOtro;
    private javax.swing.JTextField txtFTorna;
    private javax.swing.JTextField txtFTransferAdere;
    private javax.swing.JTextField txtFTransferUnical;
    // End of variables declaration//GEN-END:variables
}
